### ISSUE TITLE
Adding multiple solutions to same problem.

### ISSUE THREAD

**Issue by AnonMiraj** [MoamenAhmedMostafa/ACPC-Topic-Focused-Training-Archive#25]
Hello, 

I believe we should establish a clear naming convention for adding different solutions to the same problem. Since solutions can vary in complexity, approach, or programming language, the filename should reflect these differences. The format should be something like:

- sol(brute force).cpp
- sol(O n*k).cpp
- sol(dijkstra).cpp
- sol(hashing).java

Each filename should clearly indicate any unique aspects of the solution.

Similar instructions could be added to the pull request template.

**Comment by baraabebo10** [comment]
My opinion:
Adding multiple solutions either they are same or different and even if they are named correctly or not that is will not affect anything because If I want to get a solution of some problem I will see the easiest solution to understand so adding similar solutions will be good because everyone writes the code in the style he like.
and if different solutions were added so As I said for sure anyone will see all the repo solutions to get the most benefit.
In addition to adding similar solutions ideas but with different code is good to see all the styles of writing something like hashing may be I will use a BIT with it and maybe you will use segment tree as an example.

That is my opinion I just share it.

**Comment by AnonMiraj** [comment]
Fair enough.

But  I think we should reserve this repo for unique solutions.
If i want to see all the solutions, i could find them all in codeforces.com, and most them will be similar.

**Comment by baraabebo10** [comment]
Ok Why not maybe It will be a good way for presenting solutions I just said my opinion.

**Comment by zyadmayad** [comment]
From now on, solutions will only be accepted if they include comments explaining the steps. Please refer to the contribution section in the README file for more information.
